In [39]:
import numpy as np
list = [[
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12],
    [13,14,15]
]]
array = np.array(list)
print("Array: ",array)
print("Type: ",array.dtype)
print("Dimension: ",array.ndim)
print("Shape: ",array.shape)
print("Size: ",array.size)
print("Item_Size: ",array.itemsize)

Array:  [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]
  [13 14 15]]]
Type:  int64
Dimension:  3
Shape:  (1, 5, 3)
Size:  15
Item_Size:  8


In [50]:
import numpy as np
zero = np.zeros((2,3),dtype=int)
print(zero)

[[0 0 0]
 [0 0 0]]


In [51]:
import numpy as np
one = np.ones((2,3),dtype=int)
print(one)

[[1 1 1]
 [1 1 1]]


In [64]:
import numpy as np
full = np.full((2,3),5)
print(full)

[[5 5 5]
 [5 5 5]]


In [69]:
import numpy as np
eye = np.eye(3,dtype=int)
print(eye)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [79]:
import numpy as np
arr = np.arange(11,20,2)
print(arr)

[11 13 15 17 19]


In [93]:
import numpy as np
a = np.linspace(100,500,num=5,endpoint=True,retstep=True,dtype=int)
print(a)

(array([100, 200, 300, 400, 500]), np.float64(100.0))


In [94]:
import numpy as np
a = np.array([1,2,3,4,5])
for i in a:
  print(i)

1
2
3
4
5


In [97]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8]])
for i in a:
  print(i)

[1 2 3 4]
[5 6 7 8]


In [99]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8]])
for i in np.nditer(a):
  print(i)

1
2
3
4
5
6
7
8


In [103]:
import numpy as np
a = np.array([
    [1,2,3],
    [4,5,6]
])
for i in range(2):
  for j in range(3):
    print(a[i][j])


1
2
3
4
5
6


In [107]:
import numpy as np
a = np.array([1,2,3])
print(a[::])

[1 2 3]


In [111]:
import numpy as np
a = np.array([
    [1,2,3],
    [4,5,6]
])
print(a[0,0:3])
print(a[1,0:3])

[1 2 3]
[4 5 6]


In [112]:
import numpy as np
a = np.array([
    [1,2,3],
    [4,5,6]
])
print(a[0:2,0:4])


[[1 2 3]
 [4 5 6]]


In [120]:
import numpy as np
a = np.array([
    [1,2,3],
    [4,5,6]
])
b = np.array([
    [7,8,9],
    [10,11,12]
])

c = np.add(a,b)
d = np.subtract(a,b)
e = a*b #multiply
f = a/b #divide
g = a%b #mod(a,b)
h = np.pow(a,b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)

[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 7 16 27]
 [40 55 72]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
[[1 2 3]
 [4 5 6]]
[[         1        256      19683]
 [   1048576   48828125 2176782336]]


In [9]:
import numpy as np
a = np.array([
    [9,4,3],
    [1,7,6],
    [8,2,5]
    ])
print(a)
print("minimum: ", np.amin(a))
print("column_min: ", np.amin(a,axis=0))
print("row_min: ", np.amin(a,axis=1))
print("maximum: ", np.amax(a))
print("column_max: ", np.amax(a,axis=0))
print("row_max: ", np.amax(a,axis=1))

[[9 4 3]
 [1 7 6]
 [8 2 5]]
minimum:  1
column_min:  [1 2 3]
row_min:  [3 1 2]
maximum:  9
column_max:  [9 7 6]
row_max:  [9 7 8]


In [17]:
import numpy as np
a = np.array([
    [9,4,3],
    [1,7,6],
    [8,2,5]
])
print(a)
print("mean: ",np.mean(a))
print("col_mean: ",np.mean(a,axis=0))
print("row_mean: ",np.mean(a,axis=1))

[[9 4 3]
 [1 7 6]
 [8 2 5]]
mean:  5.0
col_mean:  [6.         4.33333333 4.66666667]
row_mean:  [5.33333333 4.66666667 5.        ]


In [18]:
import numpy as np
a = np.array([
    [9,4,3],
    [1,7,6],
    [8,2,5]
])
print(a)
print("median: ",np.median(a))
print("col_median: ",np.median(a,axis=0))
print("row_median: ",np.median(a,axis=1))

[[9 4 3]
 [1 7 6]
 [8 2 5]]
median:  5.0
col_median:  [8. 4. 5.]
row_median:  [4. 6. 5.]


In [20]:
import numpy as np
a = np.array([
    [9,4,3],
    [1,7,6],
    [8,2,5]
])
print(a)
print("variance = ",np.var(a))
print("Std_deviation = ",np.std(a))

[[9 4 3]
 [1 7 6]
 [8 2 5]]
variance =  6.666666666666667
Std_deviation =  2.581988897471611


In [31]:
import numpy as np
a = np.array([4,6,5,2,1,9,0])
print("1D Unsorted = \n",a)
print("1D Sorted = \n",np.sort(a))
b = np.array([
    [9,4,3],
    [1,7,6],
    [8,2,5]
])
print("2D Unsorted = \n",b)
print("2D Sorted = \n",np.sort(b))

1D Unsorted = 
 [4 6 5 2 1 9 0]
1D Sorted = 
 [0 1 2 4 5 6 9]
2D Unsorted = 
 [[9 4 3]
 [1 7 6]
 [8 2 5]]
2D Sorted = 
 [[3 4 9]
 [1 6 7]
 [2 5 8]]


In [38]:
import numpy as np
a = np.array([
    [1,2,3],
    [4,5,6]
])
b = np.array([
    [10,20,30],
    [40,50,60]
])
c = np.concatenate((a,b)) #default
d = np.concatenate((a,b),axis=1)
print("col_concat: \n",c)
print("row_concat: \n",d)

col_concat: 
 [[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]
row_concat: 
 [[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]


In [51]:
import numpy as np
a = np.array([1,2,3,4,5,6])
b = np.reshape(a,(2,3))
print("og_array = ",a)
print("a_shape: ",a.shape)
print("reshaped_array = \n",b)
print("b_shape: ",b.shape)

og_array =  [1 2 3 4 5 6]
a_shape:  (6,)
reshaped_array = 
 [[1 2 3]
 [4 5 6]]
b_shape:  (2, 3)


In [59]:
import numpy as np
a = np.array([
    [1,2,3],
    [4,5,6]
])

print("Transpose: \n",a.transpose())
print("tr_using_A.T: \n", a.T)

Transpose: 
 [[1 4]
 [2 5]
 [3 6]]
tr_using_A.T: 
 [[1 4]
 [2 5]
 [3 6]]


In [63]:
import numpy as np
a=np.array([7,5,1,4,6,3,7,1])
print('a[]:',a)
print(np.where(a>5))

a[]: [7 5 1 4 6 3 7 1]
(array([0, 4, 6]),)


In [78]:
import numpy as np
a = np.array([7,5,1,4,6,3,7,1])
print("Sorted_arr: ",np.sort(a))
print("Index: ", np.searchsorted(a,7))
print("Index: ", np.searchsorted(a,[4,5]))

Sorted_arr:  [1 1 3 4 5 6 7 7]
Index:  6
Index:  [3 8]
