In [39]:
import numpy as np
list = [[
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12],
    [13,14,15]
]]
array = np.array(list)
print("Array: ",array)
print("Type: ",array.dtype)
print("Dimension: ",array.ndim)
print("Shape: ",array.shape)
print("Size: ",array.size)
print("Item_Size: ",array.itemsize)

Array:  [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]
  [13 14 15]]]
Type:  int64
Dimension:  3
Shape:  (1, 5, 3)
Size:  15
Item_Size:  8


In [50]:
import numpy as np
zero = np.zeros((2,3),dtype=int)
print(zero)

[[0 0 0]
 [0 0 0]]


In [51]:
import numpy as np
one = np.ones((2,3),dtype=int)
print(one)

[[1 1 1]
 [1 1 1]]


In [64]:
import numpy as np
full = np.full((2,3),5)
print(full)

[[5 5 5]
 [5 5 5]]


In [69]:
import numpy as np
eye = np.eye(3,dtype=int)
print(eye)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [79]:
import numpy as np
arr = np.arange(11,20,2)
print(arr)

[11 13 15 17 19]


In [93]:
import numpy as np
a = np.linspace(100,500,num=5,endpoint=True,retstep=True,dtype=int)
print(a)

(array([100, 200, 300, 400, 500]), np.float64(100.0))


In [94]:
import numpy as np
a = np.array([1,2,3,4,5])
for i in a:
  print(i)

1
2
3
4
5


In [97]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8]])
for i in a:
  print(i)

[1 2 3 4]
[5 6 7 8]


In [99]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8]])
for i in np.nditer(a):
  print(i)

1
2
3
4
5
6
7
8


In [103]:
import numpy as np
a = np.array([
    [1,2,3],
    [4,5,6]
])
for i in range(2):
  for j in range(3):
    print(a[i][j])


1
2
3
4
5
6


In [107]:
import numpy as np
a = np.array([1,2,3])
print(a[::])

[1 2 3]


In [111]:
import numpy as np
a = np.array([
    [1,2,3],
    [4,5,6]
])
print(a[0,0:3])
print(a[1,0:3])

[1 2 3]
[4 5 6]


In [112]:
import numpy as np
a = np.array([
    [1,2,3],
    [4,5,6]
])
print(a[0:2,0:4])


[[1 2 3]
 [4 5 6]]


In [120]:
import numpy as np
a = np.array([
    [1,2,3],
    [4,5,6]
])
b = np.array([
    [7,8,9],
    [10,11,12]
])

c = np.add(a,b)
d = np.subtract(a,b)
e = a*b #multiply
f = a/b #divide
g = a%b #mod(a,b)
h = np.pow(a,b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)

[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 7 16 27]
 [40 55 72]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
[[1 2 3]
 [4 5 6]]
[[         1        256      19683]
 [   1048576   48828125 2176782336]]
